#!/usr/bin/env python3
"""
build.py — ระบบป้องกันแก้ผิดไฟล์
=====================================
แก้ code ที่ attendance.html (ไฟล์เดียว) แล้วรัน:
  python build.py          → สร้างทุกไฟล์
  python build.py --push   → สร้าง + commit + push GitHub Pages

ห้ามแก้ index.html / attendance-ch1.html / attendance-y2.html โดยตรง!
"""

import re, subprocess, sys, io, json
from pathlib import Path

# รองรับ Windows terminal ที่ใช้ CP874
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

ROOT      = Path(__file__).parent
TEMPLATE  = ROOT / "attendance.html"
HOMEPAGE  = ROOT / "homepage.html"

# ══════════════════════════════════════════════════════════════
#  TARGETS — เพิ่มห้องใหม่ที่นี่ที่เดียวเลย
# ══════════════════════════════════════════════════════════════
TARGETS = [

    # ── ชช.1 ──────────────────────────────────────────────────
    {
        "out":      "attendance-ch1.html",
        "label":    "attendance-ch1.html  (ชช.1)",
        "banner": """\
<!-- ╔══════════════════════════════════════════════════════════════════╗ -->
<!-- ║  ⚠️  DO NOT EDIT THIS FILE DIRECTLY                              ║ -->
<!-- ║  แก้ที่ attendance.html แล้วรัน: python build.py               ║ -->
<!-- ║  ชช.1 → https://taneech2.github.io/attendance/attendance-ch1.html ║ -->
<!-- ╚══════════════════════════════════════════════════════════════════╝ -->""",
        "patches": {
            "title_suffix":      "ชช.1 วิทยาลัยการอาชีพบุรีรัมย์",
            "db_path":           "attendance.json",
            "ls_key":            "attendanceData_v2",
            "lbl_class":         "ชช.1 สาขาวิชาช่างเชื่อมโลหะ",
            "default_students":  None,  # ใช้ค่าเดิมใน template
            "manifest":          "manifest-ch1.json",
            "pwa_name":          "เช็คชื่อ ชช.1",
            "class_subjects":    None,  # ใช้ค่าเดิมใน template
        },
    },

    # ── ชช.2 ──────────────────────────────────────────────────
    {
        "out":      "attendance-y2.html",
        "label":    "attendance-y2.html  (ชช.2)",
        "banner": """\
<!-- ╔══════════════════════════════════════════════════════════════════╗ -->
<!-- ║  ⚠️  DO NOT EDIT THIS FILE DIRECTLY                              ║ -->
<!-- ║  แก้ที่ attendance.html แล้วรัน: python build.py               ║ -->
<!-- ║  ชช.2 → https://taneech2.github.io/attendance/attendance-y2.html ║ -->
<!-- ╚══════════════════════════════════════════════════════════════════╝ -->""",
        "patches": {
            "title_suffix":      "ชช.2 วิทยาลัยการอาชีพบุรีรัมย์",
            "db_path":           "attendance-y2.json",
            "ls_key":            "attendanceData_y2_v2",
            "lbl_class":         "ชช.2 สาขาวิชาช่างเชื่อมโลหะ",
            "default_students":  "[]",
            "manifest":          "manifest-y2.json",
            "pwa_name":          "เช็คชื่อ ชช.2",
            "class_subjects": """\
[
  { id:'math_ind',   name:'คณิตอุตฯ',        full:'คณิตศาสตร์อุตสาหกรรม',               day:'จันทร์',    teacher:'อ.พรรณทิพย์' },
  { id:'eng_tech',   name:'อังกฤษช่าง',       full:'ภาษาอังกฤษเพื่องานช่าง',             day:'จันทร์',    teacher:'อ.พีรชาติ' },
  { id:'sheet',      name:'โลหะแผ่น',         full:'งานโลหะแผ่น',                         day:'อังคาร',   teacher:'อ.จักรกฤษณ์' },
  { id:'gmaw',       name:'GMAW',              full:'การเชื่อม GMAW/MIG',                  day:'อังคาร',   teacher:'อ.จักรกฤษณ์' },
  { id:'weld_math',  name:'คณิตช่างเชื่อม',  full:'คณิตศาสตร์ช่างเชื่อม',               day:'พุธ',       teacher:'อ.จักรกฤษณ์' },
  { id:'design',     name:'ออกแบบผลิตภัณฑ์',  full:'การออกแบบผลิตภัณฑ์เบื้องต้น',       day:'พุธ',       teacher:'อ.ธานี' },
  { id:'cad',        name:'CAD',               full:'เขียนแบบด้วยคอมพิวเตอร์',            day:'พฤหัสบดี', teacher:'อ.ธานี' },
  { id:'machine',    name:'เครื่องมือกล',     full:'งานเครื่องมือกลเบื้องต้น',            day:'พฤหัสบดี', teacher:'อ.สุรสิทธิ์' },
  { id:'volunteer',  name:'จิตอาสา',          full:'กิจกรรมจิตอาสา',                     day:'ศุกร์',     teacher:'อ.ธานี' },
  { id:'electric',   name:'ไฟฟ้าเบื้องต้น',   full:'ไฟฟ้าเบื้องต้นสำหรับงานช่าง',       day:'ศุกร์',     teacher:'อ.ชลธี' },
]""",
        },
    },

    # ── ช่างเชื่อม รวม ปี 1+2 (ทุนการศึกษา) ─────────────────
    {
        "out":      "attendance-weld.html",
        "label":    "attendance-weld.html  (ช่างเชื่อม รวม ปี 1+2)",
        "banner": """\
<!-- ╔══════════════════════════════════════════════════════════════════════╗ -->
<!-- ║  ⚠️  DO NOT EDIT THIS FILE DIRECTLY                                  ║ -->
<!-- ║  แก้ที่ attendance.html แล้วรัน: python build.py                   ║ -->
<!-- ║  ช่างเชื่อม รวม → https://taneech2.github.io/attendance/attendance-weld.html ║ -->
<!-- ╚══════════════════════════════════════════════════════════════════════╝ -->""",
        "patches": {
            "title_suffix":      "ช่างเชื่อม รวม ปี 1+2 วิทยาลัยการอาชีพบุรีรัมย์",
            "db_path":           "attendance-weld.json",
            "ls_key":            "attendanceData_weld_v2",
            "lbl_class":         "ช่างเชื่อมโลหะ รวม ปี 1+2 (ทุนการศึกษา)",
            "default_students":  "[]",
            "manifest":          "manifest-weld.json",
            "pwa_name":          "เช็คชื่อ ช่างเชื่อม รวม",
            "class_subjects": """\
[
  { id:'welding1',  name:'งานเชื่อมฯ (ปี1)',      full:'งานเชื่อมและโลหะแผ่นเบื้องต้น (ชช.1)',              day:'จันทร์',    teacher:'อ.ชลธี' },
  { id:'ndt',       name:'NDT (ปี1)',              full:'ทดสอบแบบไม่ทำลายสภาพ (ชช.1)',                        day:'จันทร์',    teacher:'อ.ชลธี' },
  { id:'english',   name:'อังกฤษ (ปี1)',           full:'ภาษาอังกฤษเพื่อการสื่อสาร (ชช.1)',                  day:'อังคาร',   teacher:'อ.พีรชาติ' },
  { id:'thai',      name:'ภาษาไทย (ปี1)',          full:'ภาษาไทยเพื่อการสื่อสารในงานอาชีพ (ชช.1)',           day:'อังคาร',   teacher:'อ.พรพรหม' },
  { id:'science',   name:'วิทยาศาสตร์ (ปี1)',      full:'วิทยาศาสตร์พื้นฐานอาชีพ (ชช.1)',                    day:'อังคาร',   teacher:'อ.จิดาภา' },
  { id:'math',      name:'คณิตศาสตร์ (ปี1)',       full:'คณิตศาสตร์พื้นฐานอาชีพ (ชช.1)',                     day:'พุธ',       teacher:'อ.พรรณทิพย์' },
  { id:'weldstd',   name:'มาตรฐานเชื่อม (ปี1)',    full:'มาตรฐานการเชื่อมเบื้องต้น (ชช.1)',                  day:'พุธ',       teacher:'อ.สุรสิทธิ์' },
  { id:'weldproc',  name:'กระบวนการเชื่อม (ปี1)',  full:'กระบวนการเชื่อม (ชช.1)',                             day:'พุธ',       teacher:'อ.สุรสิทธิ์' },
  { id:'digital',   name:'ดิจิทัล (ปี1)',          full:'การใช้เทคโนโลยีดิจิทัลเพื่ออาชีพ (ชช.1)',           day:'พฤหัสบดี', teacher:'อ.ธานี' },
  { id:'scout',     name:'ลูกเสือ (ปี1)',          full:'กิจกรรมลูกเสือวิสามัญ 1 (ชช.1)',                    day:'พฤหัสบดี', teacher:'อ.ธานี' },
  { id:'materials', name:'วัสดุช่าง (ปี1)',         full:'วัสดุงานช่างอุตสาหกรรม (ชช.1)',                     day:'ศุกร์',     teacher:'อ.ธานี' },
  { id:'practice',  name:'ฝึกฝีมือ (ปี1)',         full:'งานฝึกฝีมือ (ชช.1)',                                 day:'ศุกร์',     teacher:'อ.ธานี' },
  { id:'math_ind',  name:'คณิตอุตฯ (ปี2)',         full:'คณิตศาสตร์อุตสาหกรรม (ชช.2)',                       day:'จันทร์',    teacher:'อ.พรรณทิพย์' },
  { id:'eng_tech',  name:'อังกฤษช่าง (ปี2)',       full:'ภาษาอังกฤษเพื่องานช่าง (ชช.2)',                     day:'จันทร์',    teacher:'อ.พีรชาติ' },
  { id:'sheet',     name:'โลหะแผ่น (ปี2)',         full:'งานโลหะแผ่น (ชช.2)',                                 day:'อังคาร',   teacher:'อ.จักรกฤษณ์' },
  { id:'gmaw',      name:'GMAW (ปี2)',              full:'การเชื่อม GMAW/MIG (ชช.2)',                          day:'อังคาร',   teacher:'อ.จักรกฤษณ์' },
  { id:'weld_math', name:'คณิตช่างเชื่อม (ปี2)',   full:'คณิตศาสตร์ช่างเชื่อม (ชช.2)',                      day:'พุธ',       teacher:'อ.จักรกฤษณ์' },
  { id:'design',    name:'ออกแบบฯ (ปี2)',          full:'การออกแบบผลิตภัณฑ์เบื้องต้น (ชช.2)',               day:'พุธ',       teacher:'อ.ธานี' },
  { id:'cad',       name:'CAD (ปี2)',               full:'เขียนแบบด้วยคอมพิวเตอร์ (ชช.2)',                    day:'พฤหัสบดี', teacher:'อ.ธานี' },
  { id:'machine',   name:'เครื่องมือกล (ปี2)',     full:'งานเครื่องมือกลเบื้องต้น (ชช.2)',                   day:'พฤหัสบดี', teacher:'อ.สุรสิทธิ์' },
  { id:'volunteer', name:'จิตอาสา (ปี2)',          full:'กิจกรรมจิตอาสา (ชช.2)',                             day:'ศุกร์',     teacher:'อ.ธานี' },
  { id:'electric',  name:'ไฟฟ้าเบื้องต้น (ปี2)',   full:'ไฟฟ้าเบื้องต้นสำหรับงานช่าง (ชช.2)',               day:'ศุกร์',     teacher:'อ.ชลธี' },
]""",
            "merge_sources": """\
[
  {label:'ชช.1',  url:'https://attendance-bric-default-rtdb.asia-southeast1.firebasedatabase.app/attendance.json'},
  {label:'ชช.2',  url:'https://attendance-bric-default-rtdb.asia-southeast1.firebasedatabase.app/attendance-y2.json'},
]""",
        },
    },

    # ── ชย.1ก ─────────────────────────────────────────────────
    {
        "out":      "attendance-me1a.html",
        "label":    "attendance-me1a.html  (ชย.1ก)",
        "banner":   "<!-- AUTO-GENERATED from attendance.html — python build.py -->",
        "patches": {
            "title_suffix":     "ชย.1ก วิทยาลัยการอาชีพบุรีรัมย์",
            "db_path":          "attendance-me1a.json",
            "ls_key":           "attendanceData_me1a_v2",
            "lbl_class":        "ชย.1ก สาขาวิชาช่างยนต์",
            "default_students": "[]",
            "manifest":         "manifest-me1a.json",
            "pwa_name":         "เช็คชื่อ ชย.1ก",
            "class_subjects":   "[\n  { id:'scout', name:'ลูกเสือ', full:'กิจกรรมลูกเสือวิสามัญ 1', day:'พฤหัสบดี', teacher:'อ.ธานี' },\n]",
        },
    },

    # ── ชย.1ข ─────────────────────────────────────────────────
    {
        "out":      "attendance-me1b.html",
        "label":    "attendance-me1b.html  (ชย.1ข)",
        "banner":   "<!-- AUTO-GENERATED from attendance.html — python build.py -->",
        "patches": {
            "title_suffix":     "ชย.1ข วิทยาลัยการอาชีพบุรีรัมย์",
            "db_path":          "attendance-me1b.json",
            "ls_key":           "attendanceData_me1b_v2",
            "lbl_class":        "ชย.1ข สาขาวิชาช่างยนต์",
            "default_students": "[]",
            "manifest":         "manifest-me1b.json",
            "pwa_name":         "เช็คชื่อ ชย.1ข",
            "class_subjects":   "[\n  { id:'scout', name:'ลูกเสือ', full:'กิจกรรมลูกเสือวิสามัญ 1', day:'พฤหัสบดี', teacher:'อ.ธานี' },\n]",
        },
    },

    # ── ชก.1ก ─────────────────────────────────────────────────
    {
        "out":      "attendance-ml1a.html",
        "label":    "attendance-ml1a.html  (ชก.1ก)",
        "banner":   "<!-- AUTO-GENERATED from attendance.html — python build.py -->",
        "patches": {
            "title_suffix":     "ชก.1ก วิทยาลัยการอาชีพบุรีรัมย์",
            "db_path":          "attendance-ml1a.json",
            "ls_key":           "attendanceData_ml1a_v2",
            "lbl_class":        "ชก.1ก สาขาวิชาช่างกลโรงงาน",
            "default_students": "[]",
            "manifest":         "manifest-ml1a.json",
            "pwa_name":         "เช็คชื่อ ชก.1ก",
            "class_subjects":   "[\n  { id:'scout', name:'ลูกเสือ', full:'กิจกรรมลูกเสือวิสามัญ 1', day:'พฤหัสบดี', teacher:'อ.ธานี' },\n]",
        },
    },

    # ── ชก.1ข ─────────────────────────────────────────────────
    {
        "out":      "attendance-ml1b.html",
        "label":    "attendance-ml1b.html  (ชก.1ข)",
        "banner":   "<!-- AUTO-GENERATED from attendance.html — python build.py -->",
        "patches": {
            "title_suffix":     "ชก.1ข วิทยาลัยการอาชีพบุรีรัมย์",
            "db_path":          "attendance-ml1b.json",
            "ls_key":           "attendanceData_ml1b_v2",
            "lbl_class":        "ชก.1ข สาขาวิชาช่างกลโรงงาน",
            "default_students": "[]",
            "manifest":         "manifest-ml1b.json",
            "pwa_name":         "เช็คชื่อ ชก.1ข",
            "class_subjects":   "[\n  { id:'scout', name:'ลูกเสือ', full:'กิจกรรมลูกเสือวิสามัญ 1', day:'พฤหัสบดี', teacher:'อ.ธานี' },\n]",
        },
    },

    # ── ชฟ.1 ──────────────────────────────────────────────────
    {
        "out":      "attendance-el1.html",
        "label":    "attendance-el1.html   (ชฟ.1)",
        "banner":   "<!-- AUTO-GENERATED from attendance.html — python build.py -->",
        "patches": {
            "title_suffix":     "ชฟ.1 วิทยาลัยการอาชีพบุรีรัมย์",
            "db_path":          "attendance-el1.json",
            "ls_key":           "attendanceData_el1_v2",
            "lbl_class":        "ชฟ.1 สาขาวิชาช่างไฟฟ้ากำลัง",
            "default_students": "[]",
            "manifest":         "manifest-el1.json",
            "pwa_name":         "เช็คชื่อ ชฟ.1",
            "class_subjects":   "[\n  { id:'scout', name:'ลูกเสือ', full:'กิจกรรมลูกเสือวิสามัญ 1', day:'พฤหัสบดี', teacher:'อ.ธานี' },\n]",
        },
    },

    # ── คธ.1 ──────────────────────────────────────────────────
    {
        "out":      "attendance-ct1.html",
        "label":    "attendance-ct1.html   (คธ.1)",
        "banner":   "<!-- AUTO-GENERATED from attendance.html — python build.py -->",
        "patches": {
            "title_suffix":     "คธ.1 วิทยาลัยการอาชีพบุรีรัมย์",
            "db_path":          "attendance-ct1.json",
            "ls_key":           "attendanceData_ct1_v2",
            "lbl_class":        "คธ.1 สาขาวิชาคอมพิวเตอร์ธุรกิจ",
            "default_students": "[]",
            "manifest":         "manifest-ct1.json",
            "pwa_name":         "เช็คชื่อ คธ.1",
            "class_subjects":   "[\n  { id:'scout', name:'ลูกเสือ', full:'กิจกรรมลูกเสือวิสามัญ 1', day:'พฤหัสบดี', teacher:'อ.ธานี' },\n]",
        },
    },

    # ── บช.1 ──────────────────────────────────────────────────
    {
        "out":      "attendance-ac1.html",
        "label":    "attendance-ac1.html   (บช.1)",
        "banner":   "<!-- AUTO-GENERATED from attendance.html — python build.py -->",
        "patches": {
            "title_suffix":     "บช.1 วิทยาลัยการอาชีพบุรีรัมย์",
            "db_path":          "attendance-ac1.json",
            "ls_key":           "attendanceData_ac1_v2",
            "lbl_class":        "บช.1 สาขาวิชาการบัญชี",
            "default_students": "[]",
            "manifest":         "manifest-ac1.json",
            "pwa_name":         "เช็คชื่อ บช.1",
            "class_subjects":   "[\n  { id:'scout', name:'ลูกเสือ', full:'กิจกรรมลูกเสือวิสามัญ 1', day:'พฤหัสบดี', teacher:'อ.ธานี' },\n]",
        },
    },

    # ── ลูกเสือ (รวมทุกแผนก) ─────────────────────────────────
    {
        "out":      "attendance-scout.html",
        "label":    "attendance-scout.html  (ลูกเสือ รวม)",
        "banner": """\
<!-- ╔══════════════════════════════════════════════════════════════════════╗ -->
<!-- ║  ⚠️  DO NOT EDIT THIS FILE DIRECTLY                                  ║ -->
<!-- ║  แก้ที่ attendance.html แล้วรัน: python build.py                   ║ -->
<!-- ║  ลูกเสือ → https://taneech2.github.io/attendance/attendance-scout.html ║ -->
<!-- ╚══════════════════════════════════════════════════════════════════════╝ -->""",
        "patches": {
            "title_suffix":      "ลูกเสือ วิทยาลัยการอาชีพบุรีรัมย์",
            "db_path":           "attendance-scout.json",
            "ls_key":            "attendanceData_scout_v2",
            "lbl_class":         "ลูกเสือวิสามัญ ปวช.1 (รวมทุกแผนก)",
            "default_students":  "[]",
            "manifest":          "manifest-scout.json",
            "pwa_name":          "เช็คชื่อ ลูกเสือ",
            "class_subjects": """\
[
  { id:'scout', name:'ลูกเสือวิสามัญ', full:'ลูกเสือวิสามัญ (ช่างเชื่อม / ช่างยนต์ / ช่างกล / ช่างไฟฟ้า / คอมพิวเตอร์ / บัญชี)', day:'พฤหัสบดี', teacher:'อ.ธานี' },
]""",
            "merge_sources": """\
[
  {label:'ชช.1',  url:'https://attendance-bric-default-rtdb.asia-southeast1.firebasedatabase.app/attendance.json'},
  {label:'ชย.1ก', url:'https://attendance-bric-default-rtdb.asia-southeast1.firebasedatabase.app/attendance-me1a.json'},
  {label:'ชย.1ข', url:'https://attendance-bric-default-rtdb.asia-southeast1.firebasedatabase.app/attendance-me1b.json'},
  {label:'ชก.1ก', url:'https://attendance-bric-default-rtdb.asia-southeast1.firebasedatabase.app/attendance-ml1a.json'},
  {label:'ชก.1ข', url:'https://attendance-bric-default-rtdb.asia-southeast1.firebasedatabase.app/attendance-ml1b.json'},
  {label:'ชฟ.1',  url:'https://attendance-bric-default-rtdb.asia-southeast1.firebasedatabase.app/attendance-el1.json'},
  {label:'คธ.1',  url:'https://attendance-bric-default-rtdb.asia-southeast1.firebasedatabase.app/attendance-ct1.json'},
  {label:'บช.1',  url:'https://attendance-bric-default-rtdb.asia-southeast1.firebasedatabase.app/attendance-ac1.json'},
]""",
        },
    },

    # ── ลูกเสือ ชช.1 ─────────────────────────────────────────
    {
        "out":      "attendance-scout-ch1.html",
        "label":    "attendance-scout-ch1.html (ลูกเสือ ชช.1)",
        "banner":   "<!-- AUTO-GENERATED from attendance.html — python build.py -->",
        "patches": {
            "title_suffix":     "ลูกเสือ ชช.1 วิทยาลัยการอาชีพบุรีรัมย์",
            "db_path":          "attendance-scout-ch1.json",
            "ls_key":           "attendanceData_scout_ch1_v2",
            "lbl_class":        "ลูกเสือวิสามัญ ชช.1 ช่างเชื่อมโลหะ",
            "default_students": "[]",
            "manifest":         "manifest-scout-ch1.json",
            "pwa_name":         "เช็คชื่อ ลูกเสือ ชช.1",
            "class_subjects": """\
[
  { id:'scout', name:'ลูกเสือวิสามัญ', full:'ลูกเสือวิสามัญ ปวช.1 ชช.1', day:'พฤหัสบดี', teacher:'อ.ธานี' },
]""",
        },
    },

    # ── ลูกเสือ ชช.2 ─────────────────────────────────────────
    {
        "out":      "attendance-scout-y2.html",
        "label":    "attendance-scout-y2.html  (ลูกเสือ ชช.2)",
        "banner":   "<!-- AUTO-GENERATED from attendance.html — python build.py -->",
        "patches": {
            "title_suffix":     "ลูกเสือ ชช.2 วิทยาลัยการอาชีพบุรีรัมย์",
            "db_path":          "attendance-scout-y2.json",
            "ls_key":           "attendanceData_scout_y2_v2",
            "lbl_class":        "ลูกเสือวิสามัญ ชช.2 ช่างเชื่อมโลหะ",
            "default_students": "[]",
            "manifest":         "manifest-scout-y2.json",
            "pwa_name":         "เช็คชื่อ ลูกเสือ ชช.2",
            "class_subjects": """\
[
  { id:'scout', name:'ลูกเสือวิสามัญ', full:'ลูกเสือวิสามัญ ปวช.1 ชช.2', day:'พฤหัสบดี', teacher:'อ.ธานี' },
]""",
        },
    },

    # ── ลูกเสือ ชย.1ก ────────────────────────────────────────
    {
        "out":      "attendance-scout-me1a.html",
        "label":    "attendance-scout-me1a.html (ลูกเสือ ชย.1ก)",
        "banner":   "<!-- AUTO-GENERATED from attendance.html — python build.py -->",
        "patches": {
            "title_suffix":     "ลูกเสือ ชย.1ก วิทยาลัยการอาชีพบุรีรัมย์",
            "db_path":          "attendance-scout-me1a.json",
            "ls_key":           "attendanceData_scout_me1a_v2",
            "lbl_class":        "ลูกเสือวิสามัญ ชย.1ก ช่างยนต์",
            "default_students": "[]",
            "manifest":         "manifest-scout-me1a.json",
            "pwa_name":         "เช็คชื่อ ลูกเสือ ชย.1ก",
            "class_subjects": """\
[
  { id:'scout', name:'ลูกเสือวิสามัญ', full:'ลูกเสือวิสามัญ ปวช.1 ชย.1ก', day:'พฤหัสบดี', teacher:'อ.ธานี' },
]""",
        },
    },

    # ── ลูกเสือ ชย.1ข ────────────────────────────────────────
    {
        "out":      "attendance-scout-me1b.html",
        "label":    "attendance-scout-me1b.html (ลูกเสือ ชย.1ข)",
        "banner":   "<!-- AUTO-GENERATED from attendance.html — python build.py -->",
        "patches": {
            "title_suffix":     "ลูกเสือ ชย.1ข วิทยาลัยการอาชีพบุรีรัมย์",
            "db_path":          "attendance-scout-me1b.json",
            "ls_key":           "attendanceData_scout_me1b_v2",
            "lbl_class":        "ลูกเสือวิสามัญ ชย.1ข ช่างยนต์",
            "default_students": "[]",
            "manifest":         "manifest-scout-me1b.json",
            "pwa_name":         "เช็คชื่อ ลูกเสือ ชย.1ข",
            "class_subjects": """\
[
  { id:'scout', name:'ลูกเสือวิสามัญ', full:'ลูกเสือวิสามัญ ปวช.1 ชย.1ข', day:'พฤหัสบดี', teacher:'อ.ธานี' },
]""",
        },
    },

    # ── ลูกเสือ ชก.1ก ────────────────────────────────────────
    {
        "out":      "attendance-scout-ml1a.html",
        "label":    "attendance-scout-ml1a.html (ลูกเสือ ชก.1ก)",
        "banner":   "<!-- AUTO-GENERATED from attendance.html — python build.py -->",
        "patches": {
            "title_suffix":     "ลูกเสือ ชก.1ก วิทยาลัยการอาชีพบุรีรัมย์",
            "db_path":          "attendance-scout-ml1a.json",
            "ls_key":           "attendanceData_scout_ml1a_v2",
            "lbl_class":        "ลูกเสือวิสามัญ ชก.1ก ช่างกลโรงงาน",
            "default_students": "[]",
            "manifest":         "manifest-scout-ml1a.json",
            "pwa_name":         "เช็คชื่อ ลูกเสือ ชก.1ก",
            "class_subjects": """\
[
  { id:'scout', name:'ลูกเสือวิสามัญ', full:'ลูกเสือวิสามัญ ปวช.1 ชก.1ก', day:'พฤหัสบดี', teacher:'อ.ธานี' },
]""",
        },
    },

    # ── ลูกเสือ ชก.1ข ────────────────────────────────────────
    {
        "out":      "attendance-scout-ml1b.html",
        "label":    "attendance-scout-ml1b.html (ลูกเสือ ชก.1ข)",
        "banner":   "<!-- AUTO-GENERATED from attendance.html — python build.py -->",
        "patches": {
            "title_suffix":     "ลูกเสือ ชก.1ข วิทยาลัยการอาชีพบุรีรัมย์",
            "db_path":          "attendance-scout-ml1b.json",
            "ls_key":           "attendanceData_scout_ml1b_v2",
            "lbl_class":        "ลูกเสือวิสามัญ ชก.1ข ช่างกลโรงงาน",
            "default_students": "[]",
            "manifest":         "manifest-scout-ml1b.json",
            "pwa_name":         "เช็คชื่อ ลูกเสือ ชก.1ข",
            "class_subjects": """\
[
  { id:'scout', name:'ลูกเสือวิสามัญ', full:'ลูกเสือวิสามัญ ปวช.1 ชก.1ข', day:'พฤหัสบดี', teacher:'อ.ธานี' },
]""",
        },
    },

    # ── ลูกเสือ ชฟ.1 ─────────────────────────────────────────
    {
        "out":      "attendance-scout-el1.html",
        "label":    "attendance-scout-el1.html  (ลูกเสือ ชฟ.1)",
        "banner":   "<!-- AUTO-GENERATED from attendance.html — python build.py -->",
        "patches": {
            "title_suffix":     "ลูกเสือ ชฟ.1 วิทยาลัยการอาชีพบุรีรัมย์",
            "db_path":          "attendance-scout-el1.json",
            "ls_key":           "attendanceData_scout_el1_v2",
            "lbl_class":        "ลูกเสือวิสามัญ ชฟ.1 ช่างไฟฟ้ากำลัง",
            "default_students": "[]",
            "manifest":         "manifest-scout-el1.json",
            "pwa_name":         "เช็คชื่อ ลูกเสือ ชฟ.1",
            "class_subjects": """\
[
  { id:'scout', name:'ลูกเสือวิสามัญ', full:'ลูกเสือวิสามัญ ปวช.1 ชฟ.1', day:'พฤหัสบดี', teacher:'อ.ธานี' },
]""",
        },
    },

    # ── ลูกเสือ คธ.1 ─────────────────────────────────────────
    {
        "out":      "attendance-scout-ct1.html",
        "label":    "attendance-scout-ct1.html  (ลูกเสือ คธ.1)",
        "banner":   "<!-- AUTO-GENERATED from attendance.html — python build.py -->",
        "patches": {
            "title_suffix":     "ลูกเสือ คธ.1 วิทยาลัยการอาชีพบุรีรัมย์",
            "db_path":          "attendance-scout-ct1.json",
            "ls_key":           "attendanceData_scout_ct1_v2",
            "lbl_class":        "ลูกเสือวิสามัญ คธ.1 คอมพิวเตอร์ธุรกิจ",
            "default_students": "[]",
            "manifest":         "manifest-scout-ct1.json",
            "pwa_name":         "เช็คชื่อ ลูกเสือ คธ.1",
            "class_subjects": """\
[
  { id:'scout', name:'ลูกเสือวิสามัญ', full:'ลูกเสือวิสามัญ ปวช.1 คธ.1', day:'พฤหัสบดี', teacher:'อ.ธานี' },
]""",
        },
    },

    # ── ลูกเสือ บช.1 ─────────────────────────────────────────
    {
        "out":      "attendance-scout-ac1.html",
        "label":    "attendance-scout-ac1.html  (ลูกเสือ บช.1)",
        "banner":   "<!-- AUTO-GENERATED from attendance.html — python build.py -->",
        "patches": {
            "title_suffix":     "ลูกเสือ บช.1 วิทยาลัยการอาชีพบุรีรัมย์",
            "db_path":          "attendance-scout-ac1.json",
            "ls_key":           "attendanceData_scout_ac1_v2",
            "lbl_class":        "ลูกเสือวิสามัญ บช.1 การบัญชี",
            "default_students": "[]",
            "manifest":         "manifest-scout-ac1.json",
            "pwa_name":         "เช็คชื่อ ลูกเสือ บช.1",
            "class_subjects": """\
[
  { id:'scout', name:'ลูกเสือวิสามัญ', full:'ลูกเสือวิสามัญ ปวช.1 บช.1', day:'พฤหัสบดี', teacher:'อ.ธานี' },
]""",
        },
    },

]

# ══════════════════════════════════════════════════════════════
#  PATCH ENGINE — ทำงานให้ทุก target อัตโนมัติ
# ══════════════════════════════════════════════════════════════
def patch_html(html, p):
    """Apply patches dict to html string. None values = skip that patch."""

    # title
    if p.get('title_suffix'):
        html = re.sub(
            r"(<title>[^<]*?—\s*)วิทยาลัยการอาชีพบุรีรัมย์(</title>)",
            rf"\g<1>{p['title_suffix']}\g<2>",
            html,
        )

    # DB_URL path
    if p.get('db_path'):
        html = re.sub(
            r"(const DB_URL\s*=\s*'https://[^']+/)attendance(\.json')",
            rf"\g<1>{p['db_path'].replace('.json', '')}\g<2>",
            html,
        )

    # LS_KEY
    if p.get('ls_key'):
        html = html.replace(
            "const LS_KEY = 'attendanceData_v2'",
            f"const LS_KEY = '{p['ls_key']}'",
        )

    # DEFAULT_STUDENTS
    if p.get('default_students') is not None:
        html = re.sub(
            r"const DEFAULT_STUDENTS = \[[\s\S]*?\];",
            f"const DEFAULT_STUDENTS = {p['default_students']};",
            html,
        )

    # CLASS_SUBJECTS
    if p.get('class_subjects') is not None:
        html = re.sub(
            r"const CLASS_SUBJECTS = \[[\s\S]*?\];",
            f"const CLASS_SUBJECTS = {p['class_subjects']};",
            html,
        )

    # lbl-class + inp-class value
    if p.get('lbl_class') and p['lbl_class'] != 'ชช.1 สาขาวิชาช่างเชื่อมโลหะ':
        html = html.replace(
            ">ชช.1 สาขาวิชาช่างเชื่อมโลหะ<",
            f">{p['lbl_class']}<",
        )
        html = html.replace(
            'value="ชช.1 สาขาวิชาช่างเชื่อมโลหะ"',
            f'value="{p["lbl_class"]}"',
        )

    # MERGE_SOURCES
    if p.get('merge_sources') is not None:
        html = re.sub(
            r"const MERGE_SOURCES = \[[\s\S]*?\];",
            f"const MERGE_SOURCES = {p['merge_sources']};",
            html,
        )

    # PWA manifest
    if p.get('manifest'):
        html = html.replace('href="manifest.json"', f'href="{p["manifest"]}"')
    if p.get('pwa_name'):
        html = html.replace('content="เช็คชื่อ"', f'content="{p["pwa_name"]}"')

    return html


def read(path):
    return path.read_text(encoding="utf-8")

def write(path, content, label):
    path.write_text(content, encoding="utf-8")
    size = len(content) // 1024
    print(f"  ✅  {label:40s} ({size} KB)")

def add_banner(html, banner):
    return html.replace("<!DOCTYPE html>", f"<!DOCTYPE html>\n{banner}", 1)


HOMEPAGE_BANNER = """\
<!-- ╔══════════════════════════════════════════════════════════════╗ -->
<!-- ║  ⚠️  DO NOT EDIT THIS FILE DIRECTLY                          ║ -->
<!-- ║  แก้ที่ homepage.html แล้วรัน: python build.py             ║ -->
<!-- ║  HOME → https://taneech2.github.io/attendance/home.html    ║ -->
<!-- ╚══════════════════════════════════════════════════════════════╝ -->"""

REDIRECT_INDEX = """\
<!DOCTYPE html>
<!-- AUTO-REDIRECT: /attendance/ → ชช.1 (ลิงก์เดิมของผู้ปกครองยังใช้ได้) -->
<html lang="th">
<head>
<meta charset="UTF-8">
<meta http-equiv="refresh" content="0;url=attendance-ch1.html">
<title>กำลังนำไปหน้าเช็คชื่อ ชช.1...</title>
<style>
  body{background:#0a0f1e;color:#c9a84c;font-family:'Sarabun',sans-serif;
       display:flex;flex-direction:column;align-items:center;justify-content:center;
       height:100vh;gap:12px;}
  a{color:#c9a84c;font-size:13px;}
</style>
</head>
<body>
<script>window.location.replace('attendance-ch1.html');</script>
<div style="font-size:32px;">📋</div>
<div>กำลังนำไปหน้าเช็คชื่อ ชช.1...</div>
<a href="home.html">ดู Homepage ทุกห้องแทน</a>
</body>
</html>"""

def make_manifest(name, short_name, start_url, icon_emoji="📋"):
    """Generate PWA manifest dict."""
    svg = f"data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 192 192'><rect width='192' height='192' fill='%230a0f1e' rx='24'/><text x='96' y='140' font-size='110' text-anchor='middle'>{icon_emoji}</text></svg>"
    return {
        "name": name,
        "short_name": short_name,
        "start_url": start_url,
        "display": "standalone",
        "orientation": "portrait",
        "background_color": "#0a0f1e",
        "theme_color": "#c9a84c",
        "icons": [{"src": svg, "sizes": "192x192", "type": "image/svg+xml"}],
    }

def write_json(path, data, label):
    content = json.dumps(data, ensure_ascii=False, indent=2)
    path.write_text(content, encoding="utf-8")
    print(f"  ✅  {label:40s} ({len(content)//1024 or 1} KB)")

def build():
    if not TEMPLATE.exists():
        print("❌  ไม่พบ attendance.html!"); sys.exit(1)
    if not HOMEPAGE.exists():
        print("❌  ไม่พบ homepage.html!"); sys.exit(1)

    # ── Redirect index.html → ชช.1 (ลิงก์เดิมผู้ปกครองใช้ได้) ──
    write(ROOT / "index.html", REDIRECT_INDEX, "index.html  (Redirect → ชช.1)")

    # ── Homepage → home.html ─────────────────────────────────
    home_src = read(HOMEPAGE)
    print(f"📄  Template: {HOMEPAGE.name} ({len(home_src)//1024} KB)\n")
    write(ROOT / "home.html", add_banner(home_src, HOMEPAGE_BANNER), "home.html   (Homepage)")

    # ── Auto-generate manifests for targets ──────────────────
    print()
    for t in TARGETS:
        p = t.get("patches") or {}
        mf = p.get("manifest")
        if not mf: continue
        mf_path = ROOT / mf
        if mf_path.exists(): continue  # ถ้ามีอยู่แล้วไม่เขียนทับ
        pwa_name = p.get("pwa_name", "เช็คชื่อ")
        short    = pwa_name.replace("เช็คชื่อ ", "")
        url      = "./" + t["out"]
        write_json(mf_path, make_manifest(pwa_name, short, url), mf)

    # ── Attendance targets ────────────────────────────────────
    src = read(TEMPLATE)
    print(f"\n📄  Template: {TEMPLATE.name} ({len(src)//1024} KB)\n")

    for t in TARGETS:
        html = add_banner(src, t["banner"])
        if t["patches"]:
            html = patch_html(html, t["patches"])
        write(ROOT / t["out"], html, t["label"])

    print()


def git_push():
    out_files = [t["out"] for t in TARGETS]
    # รวม manifests ทุกตัว + homepage
    manifest_files = [t["patches"]["manifest"] for t in TARGETS if t.get("patches") and t["patches"].get("manifest")]
    manifest_files += ["manifest-home.json"]
    extra = list(set(manifest_files)) + ["index.html", "home.html", "homepage.html"]
    all_files = out_files + extra

    print("📦  Committing...")
    subprocess.run(["git", "add"] + all_files + ["attendance.html", "sw.js", "build.py", "CLAUDE.md"], cwd=ROOT, check=True)

    names = "index.html + " + " + ".join(t["out"] for t in TARGETS)
    result = subprocess.run(
        ["git", "commit", "-m",
         f"build: sync {names} from attendance.html\n\n"
         "Co-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>"],
        cwd=ROOT, capture_output=True, text=True,
    )
    out = result.stdout + result.stderr
    if "nothing to commit" in out:
        print("  ℹ️   ไม่มีการเปลี่ยนแปลงใหม่")
        return
    print(result.stdout.strip())
    subprocess.run(["git", "push", "origin", "main"], cwd=ROOT, check=True)
    print("  🚀  Push เรียบร้อย → GitHub Pages กำลัง deploy...")


if __name__ == "__main__":
    print("=" * 55)
    print("  🔨  Attendance Build System")
    print("=" * 55)
    build()
    if "--push" in sys.argv:
        git_push()
    else:
        print("💡  ใช้ --push เพื่อ deploy ด้วย: python build.py --push")
    print("=" * 55)
