#!/usr/bin/env python3
"""
build.py — ระบบป้องกันแก้ผิดไฟล์
=====================================
แก้ code ที่ attendance.html (ไฟล์เดียว) แล้วรัน:
  python build.py          → สร้าง index.html + attendance-y2.html
  python build.py --push   → สร้าง + commit + push GitHub Pages

ห้ามแก้ index.html หรือ attendance-y2.html โดยตรง!
"""

import re, subprocess, sys, io
from pathlib import Path

# รองรับ Windows terminal ที่ใช้ CP874
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

ROOT     = Path(__file__).parent
TEMPLATE = ROOT / "attendance.html"
INDEX    = ROOT / "index.html"
Y2       = ROOT / "attendance-y2.html"

# ══════════════════════════════════════════════
# ข้อมูลเฉพาะของ ชช.2 (patch ทับ template)
# ══════════════════════════════════════════════
Y2_PATCHES = {
    "title_suffix": "ชช.2 วิทยาลัยการอาชีพบุรีรัมย์",
    "db_path":      "attendance-y2.json",
    "ls_key":       "attendanceData_y2_v2",
    "lbl_class":    "ชช.2 สาขาวิชาช่างเชื่อมโลหะ",
    "default_students": "[]",
    "class_subjects": """\
[
  { id:'math_ind',   name:'คณิตอุตฯ',        full:'คณิตศาสตร์อุตสาหกรรม',               day:'จันทร์',    teacher:'อ.พรรณทิพย์' },
  { id:'eng_tech',   name:'อังกฤษช่าง',       full:'ภาษาอังกฤษเพื่องานช่าง',             day:'จันทร์',    teacher:'อ.พีรชาติ' },
  { id:'sheet',      name:'โลหะแผ่น',         full:'งานโลหะแผ่น',                         day:'อังคาร',   teacher:'อ.จักรกฤษณ์' },
  { id:'gmaw',       name:'GMAW',              full:'การเชื่อม GMAW/MIG',                  day:'อังคาร',   teacher:'อ.จักรกฤษณ์' },
  { id:'weld_math',  name:'คณิตช่างเชื่อม',  full:'คณิตศาสตร์ช่างเชื่อม',               day:'พุธ',       teacher:'อ.จักรกฤษณ์' },
  { id:'design',     name:'ออกแบบผลิตภัณฑ์',  full:'การออกแบบผลิตภัณฑ์เบื้องต้น',       day:'พุธ',       teacher:'อ.ธานี' },
  { id:'cad',        name:'CAD',               full:'เขียนแบบด้วยคอมพิวเตอร์',            day:'พฤหัสบดี', teacher:'อ.ธานี' },
  { id:'machine',    name:'เครื่องมือกล',     full:'งานเครื่องมือกลเบื้องต้น',            day:'พฤหัสบดี', teacher:'อ.สุรสิทธิ์' },
  { id:'volunteer',  name:'จิตอาสา',          full:'กิจกรรมจิตอาสา',                     day:'ศุกร์',     teacher:'อ.ธานี' },
  { id:'electric',   name:'ไฟฟ้าเบื้องต้น',   full:'ไฟฟ้าเบื้องต้นสำหรับงานช่าง',       day:'ศุกร์',     teacher:'อ.ชลธี' },
]""",
}

BANNER_INDEX = """\
<!-- ╔══════════════════════════════════════════════════════╗ -->
<!-- ║  ⚠️  DO NOT EDIT THIS FILE DIRECTLY                  ║ -->
<!-- ║  แก้ที่ attendance.html แล้วรัน: python build.py    ║ -->
<!-- ║  PRIMARY → https://taneech2.github.io/attendance/   ║ -->
<!-- ╚══════════════════════════════════════════════════════╝ -->"""

BANNER_Y2 = """\
<!-- ╔══════════════════════════════════════════════════════════════════╗ -->
<!-- ║  ⚠️  DO NOT EDIT THIS FILE DIRECTLY                              ║ -->
<!-- ║  แก้ที่ attendance.html แล้วรัน: python build.py               ║ -->
<!-- ║  ชช.2 → https://taneech2.github.io/attendance/attendance-y2.html ║ -->
<!-- ╚══════════════════════════════════════════════════════════════════╝ -->"""


def read(path):
    return path.read_text(encoding="utf-8")

def write(path, content, label):
    path.write_text(content, encoding="utf-8")
    size = len(content) // 1024
    print(f"  ✅  {label:35s} ({size} KB)")

def add_banner(html, banner):
    return html.replace("<!DOCTYPE html>", f"<!DOCTYPE html>\n{banner}", 1)

def patch_y2(html):
    p = Y2_PATCHES

    # title
    html = re.sub(
        r"(<title>[^<]*?—\s*)วิทยาลัยการอาชีพบุรีรัมย์(</title>)",
        rf"\g<1>{p['title_suffix']}\g<2>",
        html,
    )

    # DB_URL — เปลี่ยนเฉพาะ path ท้าย URL
    html = re.sub(
        r"(const DB_URL = 'https://[^']+/)attendance(\.json')",
        rf"\g<1>attendance-y2\g<2>",
        html,
    )

    # LS_KEY
    html = html.replace(
        "const LS_KEY = 'attendanceData_v2'",
        f"const LS_KEY = '{p['ls_key']}'",
    )

    # DEFAULT_STUDENTS (multiline array → empty)
    html = re.sub(
        r"const DEFAULT_STUDENTS = \[[\s\S]*?\];",
        f"const DEFAULT_STUDENTS = {p['default_students']};",
        html,
    )

    # CLASS_SUBJECTS (multiline)
    html = re.sub(
        r"const CLASS_SUBJECTS = \[[\s\S]*?\];",
        f"const CLASS_SUBJECTS = {p['class_subjects']};",
        html,
    )

    # lbl-class + inp-class default value
    html = html.replace(
        ">ชช.1 สาขาวิชาช่างเชื่อมโลหะ<",
        f">{p['lbl_class']}<",
    )
    html = html.replace(
        'value="ชช.1 สาขาวิชาช่างเชื่อมโลหะ"',
        f'value="{p["lbl_class"]}"',
    )

    return html


def build():
    if not TEMPLATE.exists():
        print("❌  ไม่พบ attendance.html!"); sys.exit(1)

    src = read(TEMPLATE)
    print(f"📄  Template: {TEMPLATE.name} ({len(src)//1024} KB)\n")

    # ── index.html ──────────────────────────────
    write(INDEX, add_banner(src, BANNER_INDEX), "index.html  (ชช.1)")

    # ── attendance-y2.html ───────────────────────
    y2_html = patch_y2(add_banner(src, BANNER_Y2))
    write(Y2, y2_html, "attendance-y2.html  (ชช.2)")

    print()


def git_push():
    print("📦  Committing...")
    subprocess.run(
        ["git", "add", "index.html", "attendance-y2.html"],
        cwd=ROOT, check=True,
    )
    result = subprocess.run(
        ["git", "commit", "-m",
         "build: sync index.html + attendance-y2.html from attendance.html\n\n"
         "Co-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>"],
        cwd=ROOT, capture_output=True, text=True,
    )
    out = result.stdout + result.stderr
    if "nothing to commit" in out:
        print("  ℹ️   ไม่มีการเปลี่ยนแปลงใหม่")
        return
    print(result.stdout.strip())
    subprocess.run(["git", "push", "origin", "main"], cwd=ROOT, check=True)
    print("  🚀  Push เรียบร้อย → GitHub Pages กำลัง deploy...")


if __name__ == "__main__":
    print("=" * 55)
    print("  🔨  Attendance Build System")
    print("=" * 55)
    build()
    if "--push" in sys.argv:
        git_push()
    else:
        print("💡  ใช้ --push เพื่อ deploy ด้วย: python build.py --push")
    print("=" * 55)
