#!/usr/bin/env python3
"""
build.py — ระบบป้องกันแก้ผิดไฟล์
=====================================
แก้ code ที่ attendance.html (ไฟล์เดียว) แล้วรัน:
  python build.py          → สร้างทุกไฟล์
  python build.py --push   → สร้าง + commit + push GitHub Pages

ห้ามแก้ index.html / attendance-ch1.html / attendance-y2.html โดยตรง!
"""

import re, subprocess, sys, io
from pathlib import Path

# รองรับ Windows terminal ที่ใช้ CP874
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

ROOT      = Path(__file__).parent
TEMPLATE  = ROOT / "attendance.html"
HOMEPAGE  = ROOT / "homepage.html"

# ══════════════════════════════════════════════════════════════
#  TARGETS — เพิ่มห้องใหม่ที่นี่ที่เดียวเลย
# ══════════════════════════════════════════════════════════════
TARGETS = [

    # ── ชช.1 ──────────────────────────────────────────────────
    {
        "out":      "attendance-ch1.html",
        "label":    "attendance-ch1.html  (ชช.1)",
        "banner": """\
<!-- ╔══════════════════════════════════════════════════════════════════╗ -->
<!-- ║  ⚠️  DO NOT EDIT THIS FILE DIRECTLY                              ║ -->
<!-- ║  แก้ที่ attendance.html แล้วรัน: python build.py               ║ -->
<!-- ║  ชช.1 → https://taneech2.github.io/attendance/attendance-ch1.html ║ -->
<!-- ╚══════════════════════════════════════════════════════════════════╝ -->""",
        "patches": {
            "title_suffix":      "ชช.1 วิทยาลัยการอาชีพบุรีรัมย์",
            "db_path":           "attendance.json",
            "ls_key":            "attendanceData_v2",
            "lbl_class":         "ชช.1 สาขาวิชาช่างเชื่อมโลหะ",
            "default_students":  None,  # ใช้ค่าเดิมใน template
            "manifest":          "manifest-ch1.json",
            "pwa_name":          "เช็คชื่อ ชช.1",
            "class_subjects":    None,  # ใช้ค่าเดิมใน template
        },
    },

    # ── ชช.2 ──────────────────────────────────────────────────
    {
        "out":      "attendance-y2.html",
        "label":    "attendance-y2.html  (ชช.2)",
        "banner": """\
<!-- ╔══════════════════════════════════════════════════════════════════╗ -->
<!-- ║  ⚠️  DO NOT EDIT THIS FILE DIRECTLY                              ║ -->
<!-- ║  แก้ที่ attendance.html แล้วรัน: python build.py               ║ -->
<!-- ║  ชช.2 → https://taneech2.github.io/attendance/attendance-y2.html ║ -->
<!-- ╚══════════════════════════════════════════════════════════════════╝ -->""",
        "patches": {
            "title_suffix":      "ชช.2 วิทยาลัยการอาชีพบุรีรัมย์",
            "db_path":           "attendance-y2.json",
            "ls_key":            "attendanceData_y2_v2",
            "lbl_class":         "ชช.2 สาขาวิชาช่างเชื่อมโลหะ",
            "default_students":  "[]",
            "manifest":          "manifest-y2.json",
            "pwa_name":          "เช็คชื่อ ชช.2",
            "class_subjects": """\
[
  { id:'math_ind',   name:'คณิตอุตฯ',        full:'คณิตศาสตร์อุตสาหกรรม',               day:'จันทร์',    teacher:'อ.พรรณทิพย์' },
  { id:'eng_tech',   name:'อังกฤษช่าง',       full:'ภาษาอังกฤษเพื่องานช่าง',             day:'จันทร์',    teacher:'อ.พีรชาติ' },
  { id:'sheet',      name:'โลหะแผ่น',         full:'งานโลหะแผ่น',                         day:'อังคาร',   teacher:'อ.จักรกฤษณ์' },
  { id:'gmaw',       name:'GMAW',              full:'การเชื่อม GMAW/MIG',                  day:'อังคาร',   teacher:'อ.จักรกฤษณ์' },
  { id:'weld_math',  name:'คณิตช่างเชื่อม',  full:'คณิตศาสตร์ช่างเชื่อม',               day:'พุธ',       teacher:'อ.จักรกฤษณ์' },
  { id:'design',     name:'ออกแบบผลิตภัณฑ์',  full:'การออกแบบผลิตภัณฑ์เบื้องต้น',       day:'พุธ',       teacher:'อ.ธานี' },
  { id:'cad',        name:'CAD',               full:'เขียนแบบด้วยคอมพิวเตอร์',            day:'พฤหัสบดี', teacher:'อ.ธานี' },
  { id:'machine',    name:'เครื่องมือกล',     full:'งานเครื่องมือกลเบื้องต้น',            day:'พฤหัสบดี', teacher:'อ.สุรสิทธิ์' },
  { id:'volunteer',  name:'จิตอาสา',          full:'กิจกรรมจิตอาสา',                     day:'ศุกร์',     teacher:'อ.ธานี' },
  { id:'electric',   name:'ไฟฟ้าเบื้องต้น',   full:'ไฟฟ้าเบื้องต้นสำหรับงานช่าง',       day:'ศุกร์',     teacher:'อ.ชลธี' },
]""",
        },
    },

    # ── ลูกเสือ ───────────────────────────────────────────────
    {
        "out":      "attendance-scout.html",
        "label":    "attendance-scout.html  (ลูกเสือ)",
        "banner": """\
<!-- ╔══════════════════════════════════════════════════════════════════════╗ -->
<!-- ║  ⚠️  DO NOT EDIT THIS FILE DIRECTLY                                  ║ -->
<!-- ║  แก้ที่ attendance.html แล้วรัน: python build.py                   ║ -->
<!-- ║  ลูกเสือ → https://taneech2.github.io/attendance/attendance-scout.html ║ -->
<!-- ╚══════════════════════════════════════════════════════════════════════╝ -->""",
        "patches": {
            "title_suffix":      "ลูกเสือ วิทยาลัยการอาชีพบุรีรัมย์",
            "db_path":           "attendance-scout.json",
            "ls_key":            "attendanceData_scout_v2",
            "lbl_class":         "ลูกเสือวิสามัญ ปวช.1 (รวมทุกแผนก)",
            "default_students":  "[]",
            "manifest":          "manifest-scout.json",
            "pwa_name":          "เช็คชื่อ ลูกเสือ",
            "class_subjects": """\
[
  { id:'scout', name:'ลูกเสือวิสามัญ', full:'ลูกเสือวิสามัญ (ช่างเชื่อม / ช่างยนต์ / ช่างกล / ช่างไฟฟ้า / คอมพิวเตอร์ / บัญชี)', day:'พฤหัสบดี', teacher:'อ.ธานี' },
]""",
        },
    },

]

# ══════════════════════════════════════════════════════════════
#  PATCH ENGINE — ทำงานให้ทุก target อัตโนมัติ
# ══════════════════════════════════════════════════════════════
def patch_html(html, p):
    """Apply patches dict to html string. None values = skip that patch."""

    # title
    if p.get('title_suffix'):
        html = re.sub(
            r"(<title>[^<]*?—\s*)วิทยาลัยการอาชีพบุรีรัมย์(</title>)",
            rf"\g<1>{p['title_suffix']}\g<2>",
            html,
        )

    # DB_URL path
    if p.get('db_path'):
        html = re.sub(
            r"(const DB_URL\s*=\s*'https://[^']+/)attendance(\.json')",
            rf"\g<1>{p['db_path'].replace('.json', '')}\g<2>",
            html,
        )

    # LS_KEY
    if p.get('ls_key'):
        html = html.replace(
            "const LS_KEY = 'attendanceData_v2'",
            f"const LS_KEY = '{p['ls_key']}'",
        )

    # DEFAULT_STUDENTS
    if p.get('default_students') is not None:
        html = re.sub(
            r"const DEFAULT_STUDENTS = \[[\s\S]*?\];",
            f"const DEFAULT_STUDENTS = {p['default_students']};",
            html,
        )

    # CLASS_SUBJECTS
    if p.get('class_subjects') is not None:
        html = re.sub(
            r"const CLASS_SUBJECTS = \[[\s\S]*?\];",
            f"const CLASS_SUBJECTS = {p['class_subjects']};",
            html,
        )

    # lbl-class + inp-class value
    if p.get('lbl_class') and p['lbl_class'] != 'ชช.1 สาขาวิชาช่างเชื่อมโลหะ':
        html = html.replace(
            ">ชช.1 สาขาวิชาช่างเชื่อมโลหะ<",
            f">{p['lbl_class']}<",
        )
        html = html.replace(
            'value="ชช.1 สาขาวิชาช่างเชื่อมโลหะ"',
            f'value="{p["lbl_class"]}"',
        )

    # PWA manifest
    if p.get('manifest'):
        html = html.replace('href="manifest.json"', f'href="{p["manifest"]}"')
    if p.get('pwa_name'):
        html = html.replace('content="เช็คชื่อ"', f'content="{p["pwa_name"]}"')

    return html


def read(path):
    return path.read_text(encoding="utf-8")

def write(path, content, label):
    path.write_text(content, encoding="utf-8")
    size = len(content) // 1024
    print(f"  ✅  {label:40s} ({size} KB)")

def add_banner(html, banner):
    return html.replace("<!DOCTYPE html>", f"<!DOCTYPE html>\n{banner}", 1)


HOMEPAGE_BANNER = """\
<!-- ╔══════════════════════════════════════════════════════╗ -->
<!-- ║  ⚠️  DO NOT EDIT THIS FILE DIRECTLY                  ║ -->
<!-- ║  แก้ที่ homepage.html แล้วรัน: python build.py      ║ -->
<!-- ║  HOME → https://taneech2.github.io/attendance/      ║ -->
<!-- ╚══════════════════════════════════════════════════════╝ -->"""

def build():
    if not TEMPLATE.exists():
        print("❌  ไม่พบ attendance.html!"); sys.exit(1)
    if not HOMEPAGE.exists():
        print("❌  ไม่พบ homepage.html!"); sys.exit(1)

    # ── Homepage → index.html ────────────────────────────────
    home_src = read(HOMEPAGE)
    print(f"📄  Template: {HOMEPAGE.name} ({len(home_src)//1024} KB)\n")
    write(ROOT / "index.html", add_banner(home_src, HOMEPAGE_BANNER), "index.html  (Homepage)")

    # ── Attendance targets ────────────────────────────────────
    src = read(TEMPLATE)
    print(f"\n📄  Template: {TEMPLATE.name} ({len(src)//1024} KB)\n")

    for t in TARGETS:
        html = add_banner(src, t["banner"])
        if t["patches"]:
            html = patch_html(html, t["patches"])
        write(ROOT / t["out"], html, t["label"])

    print()


def git_push():
    out_files = [t["out"] for t in TARGETS]
    extra = ["manifest-y2.json", "manifest-scout.json", "manifest-ch1.json", "manifest-home.json",
             "index.html", "homepage.html"]
    all_files = out_files + extra

    print("📦  Committing...")
    subprocess.run(["git", "add"] + all_files + ["attendance.html", "sw.js", "build.py", "CLAUDE.md"], cwd=ROOT, check=True)

    names = "index.html + " + " + ".join(t["out"] for t in TARGETS)
    result = subprocess.run(
        ["git", "commit", "-m",
         f"build: sync {names} from attendance.html\n\n"
         "Co-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>"],
        cwd=ROOT, capture_output=True, text=True,
    )
    out = result.stdout + result.stderr
    if "nothing to commit" in out:
        print("  ℹ️   ไม่มีการเปลี่ยนแปลงใหม่")
        return
    print(result.stdout.strip())
    subprocess.run(["git", "push", "origin", "main"], cwd=ROOT, check=True)
    print("  🚀  Push เรียบร้อย → GitHub Pages กำลัง deploy...")


if __name__ == "__main__":
    print("=" * 55)
    print("  🔨  Attendance Build System")
    print("=" * 55)
    build()
    if "--push" in sys.argv:
        git_push()
    else:
        print("💡  ใช้ --push เพื่อ deploy ด้วย: python build.py --push")
    print("=" * 55)
